variable "db_instance_identifier" {}
variable "instance_class" {}
variable "allocated_storage" {}
variable "db_name" {}
variable "db_username" {}
variable "db_password" {}
variable "vpc_security_group_ids" {}
variable "subnet_ids" {}
variable "create_read_replica" {}
