name: CD
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Show message
        run: echo "Deploying infrastructure an AWS ..."

      - name: Deployment
        run: |
          terraform init
          terraform apply -auto-approve

          
      - name: show message
        run: echo "Deployment complete successfully."
