name: CD
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name:
        run: |
          echo $TF_TOKEN_APP_TERRAFORM_IO
          echo $HOME
          cat .terraformrc

      - name: Login to terraform cloud
        run: |
          cp .terraformrc $HOME
          terraform init

      - name: Deployment
        run: terraform apply -auto-approve

          
      - name: show message
        run: echo "Deployment complete successfully."
